//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbApple.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefon
    {
        public int TelefonNo { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Özellik { get; set; }
        public Nullable<int> Fiyat { get; set; }
    }
}
